$('.one').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    autoplay:true,
    autoplayTimeout:1000,
    autoplayHoverPause:true,
    
    responsive:{
        0:{
            items:2
        },
        425:{
            items:3
        },
        768:{
            items:4
        },
        1024:{
            items:5
        }
    }
})

$('.two').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    autoplay:true,
    autoplayTimeout:1000,
    autoplayHoverPause:true,
    responsive:{
        0:{
            items:2
        },
        425:{
            items:3
        },
        768:{
            items:4
        },
        1024:{
            items:5
        }
    }
})